export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_REGISTERATION_FAILED = "USER_REGISTERATION_FAILED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
